---
layout: post
title: Remote conntection disconnected in FastAPI server
date: 2024-11-21 21:26:57.000000000 +08:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- agent
- API
tags:
- cocurrent processing
- fastapi
- parallel
meta:
  _last_editor_used_jetpack: block-editor
  firehose_sent: '1732195619'
  timeline_notification: '1732195621'
  _publicize_job_id: '99575607657'
  _elasticsearch_data_sharing_indexed_on: '2024-11-21 13:26:01'
  _publicize_done_external: a:1:{s:8:"facebook";a:1:{i:26861408;s:53:"https://facebook.com/1630088060609695_589992040223630";}}
  _publicize_shares: a:9:{s:6:"status";s:7:"success";s:7:"message";s:53:"https://facebook.com/1630088060609695_589992040223630";s:9:"timestamp";i:1732195627;s:7:"service";s:8:"facebook";s:13:"connection_id";i:23923317;s:11:"external_id";s:16:"1630088060609695";s:13:"external_name";s:2:"Sw";s:15:"profile_picture";s:341:"https://scontent-lax3-1.xx.fbcdn.net/v/t1.30497-1/453178253_471506465671661_2781666950760530985_n.png?stp=cp0_dst-png_s50x50&_nc_cat=110&ccb=1-7&_nc_sid=22ec41&_nc_ohc=atpU7uoQTskQ7kNvgGKIj01&_nc_zt=24&_nc_ht=scontent-lax3-1.xx&edm=AGaHXAAEAAAA&_nc_gid=AS2-rtdaBCqnpfgixjDU8ck&oh=00_AYBGwJt489aixTAoYxVdI1GqYV3ElPHt3nUr7i-wywaNkg&oe=6754457A";s:12:"profile_link";s:41:"https://www.facebook.com/1630088060609695";}
  _publicize_done_23923317: '1'
  _wpas_done_26861408: '1'
author:
  login: c013a2015
  email: c013a2015@gmail.com
  display_name: sheng gao
  first_name: sheng
  last_name: gao
permalink: "/2024/11/21/remote-conntection-disconnected-in-fastapi-server/"
---
<p><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd"><br />
<!-- wp:paragraph --><html><body></p>
<p>When I develop LLM agent based service (e.g. call openAI api async) using multiple workers to parallel processing large requests, I use uvicorn in APP code to start multiple workers. In server side, a ```remote conntection disconnected``` error happens. But from log, I can see openai request has response but in client side, it causes failure.</p>
<p><!-- /wp:paragraph --></p>
<p><!-- wp:paragraph --></p>
<p>After checking log, code and googling, still cannot find what causes the error. But following fastAPI recommendation, gunicorn is recommended in production. So I try to start server using ```gunicorn  -w n --worker-class uvicorn.workers.Uvicorn main:app```. The problem is solved. From the server log, it is found multiple workers really started working. When I use unicorn to start multiple workers, always confusing why it looks only one or few worker working, not really parallel, when monitoring CPU usage. </p>
<p><!-- /wp:paragraph --></p>
<p><!-- wp:paragraph --></p>
<p>It looks uvicorn cannot handle multiple workers and eventts scheduler, particulally when calling the outside API, which has limit request rates and a little long response time. But what is the root reason is still not understanding.   </p>
<p><!-- /wp:paragraph --><br />
</body></html></p>
